import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  Building2,
  CheckCheck,
  ClipboardList,
  ClipboardX,
  EyeOff,
  Gauge,
  Globe,
  LayoutTemplate,
  LineChart,
  Link as LinkIcon,
  ListTree,
  MapPin,
  MapPinned,
  Megaphone,
  MousePointerClick,
  PhoneCall,
  RefreshCw,
  Rocket,
  Route,
  Search,
  SearchCheck,
  Share2,
  Smartphone,
  Sparkles,
  Table2,
  Tag,
  Target,
  TrendingUp,
  Unlink,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/** خريطة أسماء الأيقونات المستخدمة في ملف البيانات إلى مكوّنات lucide. */
export const iconMap: Record<string, LucideIcon> = {
  "eye-off": EyeOff,
  smartphone: Smartphone,
  "mouse-pointer-click": MousePointerClick,
  "clipboard-x": ClipboardX,
  unlink: Unlink,
  "line-chart": LineChart,
  "layout-template": LayoutTemplate,
  globe: Globe,
  activity: Activity,
  "search-check": SearchCheck,
  target: Target,
  route: Route,
  search: Search,
  wrench: Wrench,
  "bar-chart": BarChart3,
  "refresh-cw": RefreshCw,
  "list-tree": ListTree,
  gauge: Gauge,
  "clipboard-list": ClipboardList,
  "phone-call": PhoneCall,
  tag: Tag,
  link: LinkIcon,
  "check-check": CheckCheck,
  "trending-up": TrendingUp,
  /* IXA-Leads: neue Icons für Sichtbarkeit, Werbung, Automation & Pakete */
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  megaphone: Megaphone,
  building: Building2,
  workflow: Workflow,
  table: Table2,
  rocket: Rocket,
  zap: Zap,
  sparkles: Sparkles,
  share2: Share2,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Activity;
}
